### ISSUE TITLE
index.html display

### ISSUE THREAD

**Issue by begeka** [CanadaJ/heat-of-my-meat#1]
I have a problem with displaying temperature data.
Background
I want to build a temperature logger for my fireplace in the living room on two spots 
( in the firing capacy and the exhaust) because it gives me an information of the
effectiveness of the system.
I have the MAX31855 breakout board and 
k type thermocouple. The data storage in a database and printing the data are working perfectly presently.

Problem:
I follow up the Usage and get an correct database. But the on the index.html page 
I can see only the diagram without data. All interactive buttons seems 
working correctly except the knob circle. It is gray, shows "0" in the middle
and there is no reaction on any click.

My question is this:
What important previous activity did  I overlook to let “index.html” work correctly?

**Comment by CanadaJ** [comment]
Hey begeka, 

Thanks for letting me know of this issue, it's cool to see that someone besides myself is actually using this thing!

The documentation is really lacking (something I need to get to) and I also need to do some code cleanup (something I REALLY need to get to), but I can think of a few problems:

Have you checked your web console for any JavaScript errors? The index page is all JS reliant. You should also be sure that requests are being made from your browser for the temperature values. You can do that with Chrome's developer tools.

The query_db.php file is the file that actually grabs the info out of the DB, be sure that not only the requests are being made, but that the requests are not failing with 404 messages. This can happen if query_db.php is not in the same folder as index.html.

The last thing I can think of is that Apache does not have the permissions to read from the database. Be sure to give the user running Apache these permissions.

It's been a while since I touched this project. Let me know if you have any problems with these.

**Comment by begeka** [comment]
Hey Justin,
Thank you for the promt answer. I follow your tipps and give you soon a
report.
First I can say,  that the firefox developer tools deliver a lot of errors
but I don´t
know too much about them.

2015-04-06 18:09 GMT+02:00 Justin notifications@github.com:

**Comment by CanadaJ** [comment]
If you are able to, start a fresh session and take some screenshots of the developer console. I can probably tell you right off the bat what is happening.

My gut tells me that something is happening between the JS and the PHP, maybe permissions, or a file is misplaced.

**Comment by begeka** [comment]
Hey Justin,
firstly the Screenshots. I hope they are what you ment.
Secondly my project program to measure two temperatures and time  and store
it into database.
Thirdly a project database.
Fourthly a test database I tried to open with "index.html".

2015-04-07 4:47 GMT+02:00 Justin <notifications@github.com>:

**Comment by begeka** [comment]
Hallo again,
thanks for all the touble you have with my project.
I forgot a screenshot of the autorization in the "heat-of-my-meat" folder.
Kindly regards from Germany,
Bernhard

2015-04-07 12:06 GMT+02:00 Bernhard Große-Kreul <
bernhard.grosse.kreul@gmail.com>:

**Comment by begeka** [comment]
Sorry, here I am again.

I forgot to tell you, what I did before. For learning what the programs are
doing I changed a few things:
1. The "get_temps.py ends always with a trace back and a RuntimeError:
   "The GPIO cannel has not been set up as an output".
   Using"running" in the while-loop solves that problem.
2. I want to change the thermocouple and the seeping time. Therefore I
   added two more sys.argv in the bash command (see the enclosure)

![ge_temps py](https://cloud.githubusercontent.com/assets/11679035/7218596/1069852e-e679-11e4-8258-1808f04b13b3.jpg)
3. I modified the get_temps.py to measure and store two temps. additionally I stored the measurement time and the ref time. 

![get_2db_temps py](https://cloud.githubusercontent.com/assets/11679035/7218712/763c9838-e67d-11e4-9102-fcaedcac6538.jpg)

Sincerely yours,
Bernhard.

2015-04-07 12:51 GMT+02:00 Bernhard Große-Kreul <
bernhard.grosse.kreul@gmail.com>:

**Comment by begeka** [comment]
Hallo again,
I changed the language on my browser to English an made new screenshots. So
it might be better to read for you.
All things are working well, except the html display. Is it still working
on your computer?

Sincerely yours,
Bernhard


2015-04-07 15:01 GMT+02:00 Bernhard Große-Kreul <
bernhard.grosse.kreul@gmail.com>:

**Comment by CanadaJ** [comment]
Hi begeka,

It looks like you're responding via email to this thread. Github doesn't support email attachments, you can either upload your images to somewhere like imgur.com, or drag and drop directly into the "New comment" box on Github for this issue: https://github.com/CanadaJ/heat-of-my-meat/issues/1

**Comment by begeka** [comment]
Hey Justin,
I think, that I have solved the main problem by installing php5 for sqlite3
running the following bash command:

sudo apt-get install php5-sqlite

Now I can see the temperatures on the index.html page.
I think php5  was missed to run the query_db.php file.

Bernhard.

2015-04-13 18:09 GMT+02:00 Justin notifications@github.com:

**Comment by CanadaJ** [comment]
Great! I'm sorry that the documentation is lacking. This is definitely something that should have been in a 'prerequisites' section of the README.

**Comment by begeka** [comment]
Hallo Justin,
here a complete measurement on my fireplace. What I don`t understand is the sens and the usage of the update button and the frames with min/max temperature threshold. The only effect I can get is a blue frame around the placeholders. I also tried it during the measurement with no effect.
Can you help me again please.
Bernhard  

![complete_measurement](https://cloud.githubusercontent.com/assets/11679035/7201213/130f9856-e505-11e4-9392-2e3216f8afb4.jpg)
![complete_measurement_more_comments](https://cloud.githubusercontent.com/assets/11679035/7201219/1ac36c94-e505-11e4-8121-40537f7aece1.jpg)

**Comment by begeka** [comment]
Sorry about opening and closing issue before. 
I just misunderstood the button "Close issue"

**Comment by begeka** [comment]
Hallo again,
I have two more questions:
1. I changed the size of the display using toggle tools (web developer) by edit "height: 300px" to "height: 540px" (first two pictures below). Is it possible to save this settings? The settings getting lost with every new start of index.html.  I could`t find a place to set the size in one of the heat-of-my-meat files.

The heightened display:

![large_display](https://cloud.githubusercontent.com/assets/11679035/7215168/a961c7e6-e5ca-11e4-9b47-200bbe6182d3.jpg)
More statements from the web developer tools:
![large_display_with_toggle_tools](https://cloud.githubusercontent.com/assets/11679035/7215170/b3cb2e0c-e5ca-11e4-9f96-3de0d74dda9a.jpg)
2. I am able to measure two temperatures at the same time and save it in a database (see database image below). The time and the ref columns I need for the display with Excel and can be removed.  
Is it possible to display two temperatures in the diagram of index.html?
Part of the database:
![database](https://cloud.githubusercontent.com/assets/11679035/7215247/08c1659e-e5cf-11e4-93d7-3b176a205b0b.jpg)
 Thanks a lot for helping me with my project.

**Comment by begeka** [comment]
Hey,
I solved one of my problems:
If you change defaultHigh: 300 to defaultHigh: 540 in "jquery.jqplot.min.js" one gets always the larger display of the diagram. I was quite hidden in the huge text of the file.
What I still don`t understand is the sens and the usage of the update button.
On my index.html page there is no effect clicking on the update button.

**Comment by begeka** [comment]
Hallo Justin,
I think I have basically solved my project. I can store and display two
temps of my fireplace (at firing capacity chamber  "uebb") and exhaust exit
"vbs") simultaneously.
I`m looking for an appliance of the "update button" in my project. Coloring
the knob-dial is quite useful if you measure the heat of your meat. Sorry
about my stupid questions about that.
I expected a different effect and had to learn a lot as an absolute
greenhorn  in html  programming and handling.
Thanks a lot for using your heat-of-my-meat files.
Bernhard
![abbrand_life](https://cloud.githubusercontent.com/assets/11679035/7488982/9e2bbdd6-f3d1-11e4-973d-d6e138bcda70.jpg)

![heatofmymeat_js_1](https://cloud.githubusercontent.com/assets/11679035/7444297/d3f18fd4-f17b-11e4-81c9-4bdfb97425bb.jpg)
snip
![heatofmymeat_js_2](https://cloud.githubusercontent.com/assets/11679035/7444298/d3f78c54-f17b-11e4-8179-87c1a5d2d296.jpg)
snip
![heatofmymeat_js_3](https://cloud.githubusercontent.com/assets/11679035/7444299/d3f9fea8-f17b-11e4-85f9-e3d3d85bbfe2.jpg)
snip
![heatofmymeat_js_4](https://cloud.githubusercontent.com/assets/11679035/7444300/d3fee666-f17b-11e4-9af8-7f4b2e9263b6.jpg)

2015-04-13 21:20 GMT+02:00 Justin notifications@github.com:

**Comment by begeka** [comment]
Hallo again,
why are in this issues sometimes the appendix pictures to be seen and sometimes the link only?

**Comment by CanadaJ** [comment]
Hi begeka,

Sorry I haven't been keeping up with this very much. It looks like you have figured out a lot of the answers on your own which is good. The update button is used for setting the minimum and maximum threshold temperatures. This is useful for cooking because you can set a custom range of "acceptable" temperatures. For example, if I am cooking ribs at 250f for 6 hours, I would want to set my acceptable range to 240 through 260. Anything less or more isn't good. Also, if I am cooking something like steaks or burgers, I would want to set those values really high.

As for the images not appearing, I am not seeing your latest sets of images as images, just links. I would imagine that has to do with the formatting.

**Comment by begeka** [comment]
Hallo Justin,
I just want to show you my new work. I integrated two gauges for displaying my measurements. I think it looks more technical in the way I`m studying the best way using my fireplace. It is the case, when the gap between the two temperatures is large. 
Thanks again for your splendid work. It is a helpful foundation for my work.  
![gauges](https://cloud.githubusercontent.com/assets/11679035/7587005/175c591e-f8b3-11e4-84e7-1a5be06a5e4c.jpg)
